[build]
  # Netlify will change into this directory before running build commands
  base = "jsm_banking"
  command = "npm run build"
  # Because base is already jsm_banking, publish should be the generated .next folder directly
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

[[plugins]]
  package = "@netlify/plugin-nextjs"
