[build]
  base = "jsm_banking"
  command = "npm run build"
  publish = "jsm_banking/.next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

[[plugins]]
  package = "@netlify/plugin-nextjs"
